### ISSUE TITLE
Next contribution from plan is not created if previous contr is not Completed

### ISSUE THREAD

**Issue by sluc23** [compucorp/uk.co.compucorp.membershipextras#267]
Using Offline Auto-Renew in Memberships with  Payment Plan - 1 instalment per month, 

Executing the job `OfflineAutoRenewalJob.run` to renew memberships offline and create next contributions for current month, when a recurring contribution is ready to create the next Contribution of the Plan but last Contribution is not **Completed**, next Contribution is not created

It's very usual (specially in offline payment methods as SEPA bank collections) that the Organizations tries many times to collect a payment and it could last for several weeks to accomplish it (or even until it gets **Cancelled** for any reason). For many organizations that have a monthly basis membership, having the last Contribution still not **Completed**, doesn't mean that the Membership is over or they cannot try to collect the next payment.

Is this the intended behaviour of the extensions or something you consider to adapt / accept PRs for this?

Thanks

**Comment by jamienovick** [comment]
@sluc23 actually this was something we were intending to change in a future release. 

We'd welcome a PR if you'd like to share it, preferably we would have a setting to determine this behaviour.

We're also looking to ramp up our test coverage in the not to distant future, so if you would like to add a test we would welcome that also...

I'd be interested to swap notes about how you are finding using the extension suite as well at some point - do let me know if you have time for a chat or something like that.

**Comment by sluc23** [comment]
@jamienovick i am in a testing period for this extension.. trying to see if it fits to our customers needs. Which in 75% of the cases are Membership monthly basis, paid by some kind of offline Payment Processor.
So Offline Auto-renew it's something that fits completely in this scenario, but the possibility to keep on creating next Contributions, no matter the status of the previous ones is very important as well.

we can swap notes/experiences about this whenever you feel like. thanks for your work!

**Comment by sluc23** [comment]
the validation of not having "a" pending contribution for the recurring contribution to create the next one, looks like is here:
https://patch-diff.githubusercontent.com/raw/ixiam/uk.co.compucorp.membershipextras/pull/1.patch

But I realized this extension has very complex workflows, and testing all of them for all the possible scenarios would be out of our possibilities, so i'm not submitting any PR
I will keep an eye on the evolution of this in case we can join up, at some point.

cheers!

**Comment by omarabuhussein** [comment]
FYI @sluc23 , this was done here : https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/280 and currently part of version [2.4.0 ](https://github.com/compucorp/uk.co.compucorp.membershipextras/releases/tag/2.4.0)
