### ISSUE TITLE
Payment by Installments Not Working

### ISSUE THREAD

**Issue by margaretscarson** [compucorp/uk.co.compucorp.membershipextras#512]
I am the webmaster for my client's Joomla 4 site, CIVICRM 4.4.1  
I installed Membership Extras and followed the documentation to create a New Membership.  Unfortunately, when you get to the part of the display where it asks Contribution    Payment Plans , clicking on Payment Plans does nothing.  I looked at the URL that it believes it is going to (ends in payment tab) but it does not go there.  Thus, one cannot put in the Payment Plan information.  The version of Membership Extras that I used was 6.0. 
Please advise

**Comment by jamienovick** [comment]
Hi @margaretscarson . 
Membership extras requires:
    - A patched version of CiviCRM 5.51.3, which can be found here: https://github.com/compucorp/civicrm-core/releases
Best
Jamie

**Comment by margaretscarson** [comment]
I mis-wrote.  I am CIVICRM 5.67.1.  I am obviously not going to go backward in releases.  Please advise now that you have the correct information.
