### ISSUE TITLE
Payment by Installments Not Working

### ISSUE THREAD

**Issue by margaretscarson** [compucorp/uk.co.compucorp.membershipextras#513]
Hi @margaretscarson . 
Membership extras requires:
    - A patched version of CiviCRM 5.51.3, which can be found here: https://github.com/compucorp/civicrm-core/releases
Best
Jamie

_Originally posted by @jamienovick in https://github.com/compucorp/uk.co.compucorp.membershipextras/issues/512#issuecomment-1860289768_

**Comment by margaretscarson** [comment]
I mis-wrote - I am on CIVICRM 5.67.1
I am clearly not going to go backward to a patched version.
Please advise with this corrected information.

**Comment by jamienovick** [comment]
@margaretscarson Unfortunately we do not support 5.67.1 quite yet and the extension specifically requires the patched version of CiviCRM 5.51.3, which can be found here: https://github.com/compucorp/civicrm-core/releases. Unfortunately CiviCRM can change quite significantly between versions and hence we can only support specific versions at any one time.

As mentioned on the info page: https://github.com/compucorp/uk.co.compucorp.membershipextras we are offering paid support. If you'd like to get in touch at [hello@compuco.io](mailto:hello@compuco.io) then one of the team can discuss your needs. Another option is to take a look at https://www.civi.plus/ which has this extension installed and maintained along with many more. 

Sorry we can't be more help.
